import type { Metadata } from 'next';

export const metadata: Metadata = {
   title: 'Univdatos',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
   lang,
}: Readonly<{
   children: React.ReactNode;
   lang: string;
}>) {
   return <>{children}</>;
}
