import type { Metadata } from 'next';
import '@/assets/styles/style.scss';
import Appwrapper from '@/components/Appwrapper';
import Script from 'next/script';

export const metadata: Metadata = {
   title: 'Univdatos',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang='en'>
         <body>
            <Appwrapper>{children}</Appwrapper>
            <Script id='gtranslate-settings' strategy='afterInteractive'>
               {`window.gtranslateSettings = {"default_language":"en","url_structure":"sub_directory","languages":["en","fr","it","es"],"wrapper_selector":".gtranslate_wrapper"}`}
            </Script>
            <Script
               src='https://cdn.gtranslate.net/widgets/latest/dropdown.js'
               defer
            ></Script>
         </body>
      </html>
   );
}
